import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, Clock3, Trash2 } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useHistory } from "@/hooks/useHistory";
import { clearResults, deleteResult } from "@/infrastructure/indexedDb";
import { clearAllLocalStorage } from "@/infrastructure/localStorage";
import { QUESTION_VERSION, SCORING_VERSION } from "@/constants/versions";
import { dateLocaleFor } from "@/i18n/dateLocale";

export function HistoryPage() {
  const { t, i18n } = useTranslation();
  const { records, loading, refresh } = useHistory();
  const [target, setTarget] = useState<string | null>(null);
  const remove = async () => { if (target) await deleteResult(target); setTarget(null); await refresh(); };
  const clear = async () => { await clearResults(); clearAllLocalStorage(); setTarget(null); await refresh(); };
  const clearHistoryOnly = async () => { await clearResults(); setTarget(null); await refresh(); };
  return <div className="mx-auto max-w-4xl space-y-8 py-5 sm:py-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold tracking-[0.16em] text-blue-700">{t("history.eyebrow")}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{t("history.title")}</h1><p className="mt-3 text-muted-foreground">{t("history.subtitle")}</p></div>{!loading && records.length > 0 && <span className="rounded-full bg-blue-50 px-3 py-1.5 text-sm font-semibold text-blue-700">{t("history.recordCount", { count: records.length })}</span>}</header>
    {loading ? <div className="rounded-2xl border border-slate-200 p-8 text-sm text-muted-foreground">{t("history.loading")}</div> : records.length === 0 ? <EmptyState /> : <><section className="space-y-3">{records.map((record, index) => { const previous = records[index + 1]; const diff = previous ? record.result.totalScore - previous.result.totalScore : null; const current = index === 0; return <article key={record.id} className={`rounded-2xl border p-5 shadow-sm sm:p-6 ${current ? "border-blue-200 bg-blue-50/40" : "border-slate-200 bg-white"}`}><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex gap-4"><div className={`flex size-14 shrink-0 flex-col items-center justify-center rounded-2xl ${current ? "bg-blue-700 text-white" : "bg-slate-100 text-slate-800"}`}><strong className="text-lg leading-none">{record.result.totalScore}</strong><span className="mt-1 text-[10px]">SCORE</span></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-950">{t("result.levelLabel", { level: record.result.level })}</h2>{current && <Badge className="bg-blue-700">{t("history.latestBadge")}</Badge>}{(record.questionVersion !== QUESTION_VERSION || record.scoringVersion !== SCORING_VERSION) && <Badge variant="secondary">{t("history.outdatedBadge")}</Badge>}</div><p className="mt-1 flex items-center gap-1.5 text-sm text-muted-foreground"><Clock3 className="size-3.5" />{new Date(record.createdAt).toLocaleString(dateLocaleFor(i18n.language))} ・ {record.tier === "quick" ? t("common.tierQuick") : t("common.tierStandard")}</p>{diff !== null && <p className={`mt-3 text-sm font-medium ${diff >= 0 ? "text-emerald-700" : "text-rose-700"}`}>{diff >= 0 ? t("common.diffPointsPositive", { diff }) : t("common.diffPointsNegative", { diff })}</p>}</div></div><div className="flex gap-2"><Button size="sm" asChild><Link to={`/result/${record.id}`}>{t("history.viewResultButton")} <ArrowRight /></Link></Button><Button size="icon-sm" variant="ghost" aria-label={t("history.deleteAriaLabel")} onClick={() => setTarget(record.id)}><Trash2 /></Button></div></div></article>; })}</section><section className="rounded-2xl border border-rose-100 bg-rose-50/50 p-5"><h2 className="font-semibold text-slate-950">{t("history.dataManagementTitle")}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{t("history.dataManagementBody")}</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" disabled={!records.length} onClick={() => setTarget("history")}>{t("history.clearHistoryButton")}</Button><Button variant="destructive" disabled={!records.length} onClick={() => setTarget("all")}>{t("history.clearAllButton")}</Button></div></section></>}
    <Dialog open={target !== null} onOpenChange={(open) => !open && setTarget(null)}><DialogContent><DialogHeader><DialogTitle>{target === "all" ? t("history.confirmDeleteAllTitle") : target === "history" ? t("history.confirmDeleteHistoryTitle") : t("history.confirmDeleteOneTitle")}</DialogTitle><DialogDescription>{t("history.confirmDeleteBody")}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setTarget(null)}>{t("history.cancelButton")}</Button><Button variant="destructive" onClick={() => void (target === "all" ? clear() : target === "history" ? clearHistoryOnly() : remove())}>{t("history.confirmDeleteButton")}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function EmptyState() { const { t } = useTranslation(); return <section className="rounded-3xl border border-dashed border-slate-300 bg-slate-50 px-6 py-14 text-center"><span className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-blue-100 text-blue-700"><BarChart3 className="size-6" /></span><h2 className="mt-5 text-xl font-semibold text-slate-950">{t("history.emptyTitle")}</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{t("history.emptyBody")}</p><Button asChild size="lg" className="mt-6"><Link to="/assessments">{t("history.emptyButton")}</Link></Button></section>; }
