import { AXIS_POINTS, applicableQuestions, coefficientOf } from "./questions";
import type { Answers, Recommendation, Tier } from "./types";

// docs/design/02-recommendations-catalog.md の確定カタログ(priority は 01-scoring-spec.md §11 の優先度マップ)
export const RECOMMENDATIONS: Recommendation[] = [
  { id: "imp-Q01", category: "project", priority: "medium",
    title: "開発フェーズに応じたAI活用計画の策定",
    description: "開発種別によりAI活用の適用範囲・リスクが大きく異なります。特にレガシー刷新や企画検討段階では基盤整備が先決です。",
    action: "開発フェーズを明確化し、フェーズに応じたAI活用ロードマップを策定します。",
    expectedEffect: "非現実的な期待値設定を防ぎ、段階的で確実なAI導入ができます。",
    relatedQuestionIds: ["Q01"] },
  { id: "imp-Q02", category: "project", priority: "low",
    title: "開発対象ドメインの技術的特性の把握",
    description: "組込み制御・データ分析MLなど、一般的なAIコーディング支援の実績が薄い領域では慎重な導入が必要です。",
    action: "対象ドメインに特化したAIツールやプロンプト設計を検討します。",
    expectedEffect: "ドメイン特性を踏まえたツール選定によりミスマッチを回避できます。",
    relatedQuestionIds: ["Q02"] },
  { id: "imp-Q03", category: "project", priority: "low",
    title: "一般的な技術スタックへの移行検討",
    description: "AIは広く使われている技術ほど高精度な支援ができます。独自・希少技術ではAI活用効果が限定的です。",
    action: "長期的な技術選定方針として、広く使われている技術スタックの採用を検討します。",
    expectedEffect: "AIコーディング支援の的中率・提案品質が向上します。",
    relatedQuestionIds: ["Q03"] },
  { id: "imp-Q04", category: "project", priority: "low",
    title: "仕様理解の属人化解消",
    description: "特定の担当者に仕様理解が依存していると、AI活用時のレビュー・検証体制が機能しません。",
    action: "仕様理解を複数人に共有するためのペア作業やドキュメント化を実施します。",
    expectedEffect: "AI生成物の検証体制が強化され、実装工程の適性が向上します。",
    relatedQuestionIds: ["Q04"] },
  { id: "imp-Q05", category: "document", priority: "medium",
    title: "README・環境構築手順の整備",
    description: "READMEの不備は、新規参加者とAIツールの双方にとって開発コンテキスト理解の大きな障壁になります。",
    action: "プロジェクト概要・セットアップ手順・起動方法・テスト方法をREADMEに明記し、定期的に検証します。",
    expectedEffect: "AIコーディングツールが正しい開発コンテキストを参照できるようになります。",
    relatedQuestionIds: ["Q05"] },
  { id: "imp-Q06", category: "document", priority: "high",
    title: "チャット上の仕様を正式文書へ移す",
    description: "仕様がチャットやメールに分散している、またはほとんど残っていない状態は、総合スコアの上限に直結する重大なリスクです。",
    action: "Wikiやドキュメント管理ツールへ要件・仕様を集約し、更新フローを定義します。",
    expectedEffect: "AIが仕様を参照して実装できるようになり、総合スコアの上限制約も解除されます。",
    relatedQuestionIds: ["Q06"] },
  { id: "imp-Q07", category: "document", priority: "medium",
    title: "ADR(設計判断記録)を導入する",
    description: "設計判断の背景が記録されていないと、AIが過去の意思決定を踏まえた一貫性のある提案を行えません。",
    action: "まずはテンプレートを用意し、今後の重要な設計判断から記録を開始します。",
    expectedEffect: "AIが設計意図を理解し、過去の判断と矛盾する提案を減らせます。",
    relatedQuestionIds: ["Q07"] },
  { id: "imp-Q08", category: "document", priority: "medium",
    title: "コーディングガイドラインを整備する",
    description: "規約が未整備だとAI生成コードのスタイルが不揃いになり、レビューコストが増大します。",
    action: "既存コードから規約を抽出し、AIが参照できる形で文書化します。",
    expectedEffect: "AI生成コードの一貫性が向上し、レビュー負荷が下がります。",
    relatedQuestionIds: ["Q08"] },
  { id: "imp-Q09", category: "document", priority: "low",
    title: "API仕様・外部連携仕様の文書化",
    description: "API仕様が未整備だと、AIが誤ったインターフェースでコードを生成するリスクが高まります。",
    action: "OpenAPIなどの形式でAPI仕様を整備し、実装との同期を保つ仕組みを導入します。",
    expectedEffect: "外部連携を含む実装でのAI誤生成リスクを低減できます。",
    relatedQuestionIds: ["Q09"] },
  { id: "imp-Q10", category: "document", priority: "low",
    title: "DB設計・データ項目の文書化",
    description: "データモデルの文書化不足は、AIによるデータ整合性を伴う実装の障害になります。",
    action: "ER図やデータ項目定義を整備し、変更時の更新ルールを定めます。",
    expectedEffect: "データ関連実装でのAI誤生成リスクを低減できます。",
    relatedQuestionIds: ["Q10"] },
  { id: "imp-Q11", category: "document", priority: "low",
    title: "業務ルール・例外処理の文書化",
    description: "暗黙知になっている業務ルールはAIが把握できず、重大な仕様漏れの原因になります。",
    action: "業務ルールと例外パターンをドキュメントまたはテストケースとして明文化します。",
    expectedEffect: "要件整理・実装工程でのAI活用時の手戻りを削減できます。",
    relatedQuestionIds: ["Q11"] },
  { id: "imp-Q12", category: "document", priority: "low",
    title: "過去の障害・既知問題のナレッジ化",
    description: "過去の障害記録がないと同種の問題を繰り返すリスクがあり、AIも参照できません。",
    action: "障害報告や注意事項を検索可能な場所に蓄積します。",
    expectedEffect: "運用・障害対応工程でのAI活用適性が向上します。",
    relatedQuestionIds: ["Q12"] },
  { id: "imp-Q13", category: "process", priority: "high",
    title: "Gitによるバージョン管理へ移行する",
    description: "Git未使用は変更履歴の追跡やAI生成コードの差分レビューを著しく困難にし、総合スコア上限の直接要因です。",
    action: "すべてのソースコードをGitリポジトリへ移行し、基本的なブランチ運用ルールを整備します。",
    expectedEffect: "AI駆動開発の前提が整い、総合スコアの上限制約が解除されます。",
    relatedQuestionIds: ["Q13"] },
  { id: "imp-Q14", category: "process", priority: "low",
    title: "コミットメッセージ規約の導入",
    description: "コミット履歴から変更目的が読み取れないと、人間もAIも変更の意図を理解できません。",
    action: "変更目的やチケット番号を含めるコミットメッセージ規約を導入します。",
    expectedEffect: "変更履歴の可読性が上がり、AIによる差分理解の精度が向上します。",
    relatedQuestionIds: ["Q14"] },
  { id: "imp-Q15", category: "process", priority: "high",
    title: "Pull Requestレビュー体制を確立する",
    description: "人間によるレビューがない状態はAI生成コードの検証機会を失わせ、総合スコア上限の要因になります。",
    action: "Pull Request / Merge Requestベースの開発フローとレビュー必須化を導入します。",
    expectedEffect: "AI生成コードを安全に取り込めるようになり、総合スコアの上限制約が解除されます。",
    relatedQuestionIds: ["Q15"] },
  { id: "imp-Q16", category: "process", priority: "high",
    title: "チケット管理ツールを導入する",
    description: "チケット管理がないとタスクの粒度・進捗が不透明になり、総合スコア上限の要因になります。",
    action: "GitHub IssuesやJiraなどのチケット管理ツールを導入し、運用を定着させます。",
    expectedEffect: "AIに依頼できるタスク単位が明確になり、総合スコアの上限制約が解除されます。",
    relatedQuestionIds: ["Q16"] },
  { id: "imp-Q17", category: "process", priority: "medium",
    title: "チケットに目的・要件・完了条件を記載する",
    description: "完了条件が曖昧だと、AIへのタスク依頼粒度が定まらず、成果物の検証基準も不明確になります。",
    action: "チケットテンプレートに目的・要件・完了条件を必須項目として追加します。",
    expectedEffect: "AIへのタスク委譲の精度が向上し、推定削減率の押し上げ要因になります。",
    relatedQuestionIds: ["Q17"] },
  { id: "imp-Q18", category: "process", priority: "low",
    title: "タスクを適切な粒度に分割する",
    description: "粗すぎるタスクはAIへの指示が曖昧になり、生成コードの検証コストが増大します。",
    action: "数時間から数日で完了する単位へタスクを分割する運用を徹底します。",
    expectedEffect: "AIエージェントに任せられるタスクが増え、レビュー負荷が軽減します。",
    relatedQuestionIds: ["Q18"] },
  { id: "imp-Q19", category: "process", priority: "low",
    title: "開発〜リリース手順の標準化",
    description: "手順が属人化・未定義だと、AI活用を組み込んだ標準フローを構築できません。",
    action: "開発からリリースまでの手順書を作成し、チームに周知します。",
    expectedEffect: "AI活用を含む開発フロー全体の再現性が高まります。",
    relatedQuestionIds: ["Q19"] },
  { id: "imp-Q20", category: "process", priority: "medium",
    title: "CI/CDまたは自動ビルドを構築する",
    description: "自動ビルド・自動チェックが未整備だと、AI生成コードの検証サイクルが長期化します。",
    action: "ビルド・テスト・静的チェックを自動化するパイプラインを構築します。",
    expectedEffect: "AI生成コードを高速かつ安全に検証でき、推定削減率の押し上げ要因になります。",
    relatedQuestionIds: ["Q20"] },
  { id: "imp-Q33", category: "process", priority: "medium",
    title: "小さなコミットとロールバック運用を定着させる",
    description: "AI活用では変更量が増えやすく、細かいコミットと戻せる運用がないと問題発生時の切り戻しが困難になります。",
    action: "作業を小さな単位でコミットする運用と、revertなどで安全に戻す手順をチームで定着させます。",
    expectedEffect: "AIによる変更を安全に取り込み、問題発生時に迅速に復旧できます。",
    relatedQuestionIds: ["Q33"] },
  { id: "imp-Q21", category: "qa", priority: "high",
    title: "自動テストを整備する",
    description: "自動テストの不在はAI生成コードの安全網を失わせる重大なリスクです。",
    action: "重要な機能から単体テストを段階的に整備し、CIに組み込みます。",
    expectedEffect: "AI生成コードの品質を機械的に担保でき、総合スコアの上限制約も解除されます。",
    relatedQuestionIds: ["Q21"] },
  { id: "imp-Q22", category: "qa", priority: "high",
    title: "変更後の確認項目を明確にする",
    description: "確認項目が未定義だと、変更(特にAIによる変更)の影響を検証できません。",
    action: "変更種別ごとの確認チェックリストを整備します。",
    expectedEffect: "AI生成コードの検証が確実になり、総合スコアの上限制約も解除されます。",
    relatedQuestionIds: ["Q22"] },
  { id: "imp-Q23", category: "qa", priority: "low",
    title: "コードレビュー基準の明文化",
    description: "レビュー基準が属人的だと品質判定がばらつき、AI生成コードの評価も一貫しません。",
    action: "セキュリティ・可読性・性能などのレビュー観点を明文化しチェックリスト化します。",
    expectedEffect: "コードレビュー工程のAI活用適性が向上します。",
    relatedQuestionIds: ["Q23"] },
  { id: "imp-Q24", category: "qa", priority: "low",
    title: "静的解析・Lint・型チェックの自動化",
    description: "自動チェックがないと、AI生成コードの機械的な品質担保ができません。",
    action: "Lint・型チェック・静的解析ツールをCIに組み込みます。",
    expectedEffect: "AI生成コードの明らかな問題を自動検出でき、レビュー負荷が軽減します。",
    relatedQuestionIds: ["Q24"] },
  { id: "imp-Q25", category: "qa", priority: "high",
    title: "本番反映前の人間承認プロセスを確立する",
    description: "人間による承認の欠如は、AI活用時の安全性を損なう総合スコア上限の要因です。",
    action: "本番反映前に必ず人間の承認ステップを設けるフローを構築します。",
    expectedEffect: "AIを活用しても安全にリリースでき、総合スコアの上限制約が解除されます。",
    relatedQuestionIds: ["Q25"] },
  { id: "imp-Q26", category: "qa", priority: "medium",
    title: "機密情報・個人情報の取扱ルールを整備する",
    description: "取扱ルールが未整備だと、AIツール利用時の情報漏えいリスクが高まります。",
    action: "機密情報・個人情報の分類基準と取扱ルールを策定し、周知します。",
    expectedEffect: "情報漏えいリスクが下がり、AI入力ルール整備の前提が整います。",
    relatedQuestionIds: ["Q26"] },
  { id: "imp-Q27", category: "ai", priority: "low",
    title: "AIコーディングツールの導入を広げる",
    description: "AI利用が未実施・試験段階に留まっていると、効果測定や体制整備が進みません。",
    action: "小規模なパイロット導入を実施し、効果と課題を記録します。",
    expectedEffect: "AI活用の実績データが蓄積され、本格展開の判断材料が得られます。",
    relatedQuestionIds: ["Q27"] },
  { id: "imp-Q28", category: "ai", priority: "high",
    title: "AIへの入力禁止情報を定義する",
    description: "AIに入力してよい情報・禁止情報のルールがないと、機密情報漏えいのリスクが高く、総合スコア上限の要因になります。",
    action: "機密区分ごとにAIツールへの入力可否基準を策定し、ツール設定とあわせて運用します。",
    expectedEffect: "安全にAIを利用できるようになり、総合スコアの上限制約が解除されます。",
    relatedQuestionIds: ["Q28"] },
  { id: "imp-Q29", category: "ai", priority: "low",
    title: "AI生成コードのレビュールールを策定する",
    description: "AI生成コード特有の観点(誤った前提・ライセンスなど)が未整備だと品質リスクが残ります。",
    action: "AI生成コード向けのレビューチェックリストを策定します。",
    expectedEffect: "AI生成コードを安心して取り込める体制が整います。",
    relatedQuestionIds: ["Q29"] },
  { id: "imp-Q30", category: "ai", priority: "low",
    title: "AI参照用ガイドライン・指示ファイルを整備する",
    description: "AIツール向けの指示ファイルがないと、AI生成物の一貫性を確保しにくくなります。",
    action: "コーディング規約や設計方針をAGENTS.md・CLAUDE.mdなどのAI参照用ファイルとして整備します。",
    expectedEffect: "AI生成コードの一貫性と精度が向上します。",
    relatedQuestionIds: ["Q30"] },
  { id: "imp-Q31", category: "ai", priority: "low",
    title: "AI利用効果の測定指標を導入する",
    description: "効果指標がないと投資対効果を説明できず、AI活用拡大の意思決定が遅れます。",
    action: "実装時間・レビュー時間・不具合数などのKPIを定義し、継続的に計測します。",
    expectedEffect: "AI導入の意思決定材料が整い、継続的な改善が可能になります。",
    relatedQuestionIds: ["Q31"] },
  { id: "imp-Q32", category: "ai", priority: "low",
    title: "AI導入の推進担当者を決める",
    description: "推進担当が不在だと、AI活用のルール整備や展開が場当たり的になります。",
    action: "AI導入の責任者・推進担当者を任命し、ガイドライン更新やツール選定の体制を整えます。",
    expectedEffect: "AI活用が組織的に継続・拡大できるようになります。",
    relatedQuestionIds: ["Q32"] },
  { id: "imp-Q34", category: "ai", priority: "medium",
    title: "AIが社内データを参照できる環境を整える",
    description: "AIツールが仕様書・コードベース・ナレッジを参照できない状態では、コンテキスト不足により生成物の品質が頭打ちになります。",
    action: "機密情報の取扱ルールに従った上で、リポジトリ内ドキュメントの整備やツール連携により、AIが社内データを参照できる状態を整えます。",
    expectedEffect: "AI出力の正確性・一貫性が向上し、手戻りが減ります。",
    relatedQuestionIds: ["Q34"] },
];

const priorityOrder = { high: 0, medium: 1, low: 2 } as const;
export const selectStrengths = (tier: Tier, answers: Answers) => {
  const applicable = applicableQuestions(tier, answers); const candidates = applicable.filter((question) => coefficientOf(question.id, answers) === 1);
  const pool = candidates.length >= 3 ? candidates : applicable.filter((question) => (coefficientOf(question.id, answers) ?? -1) >= .6);
  const chosen: typeof pool = []; const axes = new Set<string>();
  for (const question of [...pool].sort((a, b) => AXIS_POINTS[b.axis] - AXIS_POINTS[a.axis])) if (!axes.has(question.axis) && chosen.length < 3) { chosen.push(question); axes.add(question.axis); }
  for (const question of pool) if (!chosen.includes(question) && chosen.length < 3) chosen.push(question);
  return chosen.map((question) => ({ questionId: question.id, text: question.strengthText }));
};
export const generateRecommendations = (tier: Tier, answers: Answers) => {
  const applicable = applicableQuestions(tier, answers); const counts = new Map(applicable.map((question) => [question.axis, applicable.filter((item) => item.axis === question.axis).length]));
  const entries = applicable.flatMap((question) => {
    const coefficient = coefficientOf(question.id, answers); const eligible = coefficient !== null && coefficient < 1 && question.id !== "Q02" && (question.id !== "Q01" || ["legacy_renewal", "planning_phase", "maintenance"].includes(answers.Q01));
    if (!eligible) return [];
    const recommendation = RECOMMENDATIONS.find((item) => item.relatedQuestionIds[0] === question.id)!;
    return [{ recommendation, impact: (AXIS_POINTS[question.axis] / (counts.get(question.axis) ?? 1)) * (1 - coefficient) }];
  }).sort((a, b) => priorityOrder[a.recommendation.priority] - priorityOrder[b.recommendation.priority] || b.impact - a.impact);
  const issues = entries.map((entry) => entry.recommendation);
  const high = entries.filter((entry) => entry.recommendation.priority === "high"); const medium = entries.filter((entry) => entry.recommendation.priority === "medium"); const low = entries.filter((entry) => entry.recommendation.priority === "low");
  return { issues, nextSteps: { now: high.map((entry) => entry.recommendation), within1Month: medium.slice(0, 5).map((entry) => entry.recommendation), within3Months: [...medium.slice(5), ...low].sort((a, b) => b.impact - a.impact).map((entry) => entry.recommendation) } };
};
